services:
  - type: web
    name: weddmate-api
    runtime: node
    plan: free
    rootDir: backend

    buildCommand: npm install && npx prisma generate && npm run build

    startCommand: npm start

    envVars:

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: JWT_EXPIRES_IN
        value: 7d

      - key: APP_BASE_URL
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_KEY
        sync: false

      - key: BUCKET_NAME
        value: weddmate-photos

      - key: BUCKET_QR
        value: weddmate-qrcodes

      - key: WHATSAPP_TOKEN
        sync: false

      - key: WHATSAPP_PHONE_ID
        sync: false